[package]
name = "purrcode-tui"
version.workspace = true
edition = "2024"
license.workspace = true

[dependencies]
purrcode-terminal-runtime = { path = "../terminal-runtime" }
anyhow.workspace = true
textwrap.workspace = true
chrono.workspace = true
crossterm.workspace = true
directories.workspace = true
futures.workspace = true
purrcode-runtime-core = { path = "../runtime-core" }
purrcode-provider-import = { path = "../provider-import" }
ratatui = { workspace = true, features = ["serde"] }
reqwest.workspace = true
rpassword.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
unicode-segmentation.workspace = true
unicode-width.workspace = true
uuid.workspace = true
zeroize.workspace = true

[dev-dependencies]
tempfile.workspace = true